
-- Disable all FK
EXEC sp_MSforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT ALL"

-- Truncate tables in order
TRUNCATE TABLE [dbo].[CHI_TIET_HOA_DON];
TRUNCATE TABLE [dbo].[HOA_DON_MUA_VE];
TRUNCATE TABLE [dbo].[VE_XE];
TRUNCATE TABLE [dbo].[PHAN_CONG];
TRUNCATE TABLE [dbo].[CHUYEN_XE];
TRUNCATE TABLE [dbo].[CHI_TIET_TUYEN_XE];
TRUNCATE TABLE [dbo].[TUYEN_XE];
TRUNCATE TABLE [dbo].[GHE];
TRUNCATE TABLE [dbo].[XE];
TRUNCATE TABLE [dbo].[DIEM_DON_TRA];
TRUNCATE TABLE [dbo].[NHAN_VIEN];
TRUNCATE TABLE [dbo].[KHACH_HANG];
TRUNCATE TABLE [dbo].[LOAI_XE];

-- Enable all FK
EXEC sp_MSforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL"
